
version: '3'
services:
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

  mariadb:
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./maria-db:/var/lib/mysql
