version: '3'
services:
  app:
    image: skyline9981/ticton-oracle-bot:develop
    platform: linux/amd64
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - mariadb

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  mariadb:
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./maria-db:/var/lib/mysql
