version: '3'
services:
  app:
    image: skyline9981/ticton-oracle-bot:1-containerize-the-bot
    platform: linux/amd64
    restart: always
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
      - mariadb

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

  mariadb:
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - maria-db:/var/lib/mysql

volumes:
  maria-db:
